# Generated by Django 3.2 on 2021-05-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_id', models.CharField(max_length=100)),
                ('totalcase', models.BigIntegerField(null=True)),
                ('newcase', models.BigIntegerField(null=True)),
                ('totaldeath', models.BigIntegerField(null=True)),
                ('newdeath', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_id', models.CharField(max_length=100)),
                ('parent_id', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.data')),
            ],
        ),
    ]
