# Generated by Django 3.2 on 2021-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('totalcase', models.BigIntegerField(null=True)),
                ('newcase', models.BigIntegerField(null=True)),
                ('totaldeath', models.BigIntegerField(null=True)),
                ('newdeath', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('totalcase', models.BigIntegerField(null=True)),
                ('newcase', models.BigIntegerField(null=True)),
                ('totaldeath', models.BigIntegerField(null=True)),
                ('newdeath', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('totalcase', models.BigIntegerField(null=True)),
                ('newcase', models.BigIntegerField(null=True)),
                ('totaldeath', models.BigIntegerField(null=True)),
                ('newdeath', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('totalcase', models.BigIntegerField(null=True)),
                ('newcase', models.BigIntegerField(null=True)),
                ('totaldeath', models.BigIntegerField(null=True)),
                ('newdeath', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
