# Generated by Django 3.2 on 2021-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_world_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='world',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.RemoveField(
            model_name='area',
            name='state',
        ),
        migrations.RemoveField(
            model_name='area',
            name='world',
        ),
        migrations.RemoveField(
            model_name='country',
            name='world',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='world',
        ),
        migrations.AlterField(
            model_name='area',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateField(),
        ),
    ]
