# Generated by Django 3.2 on 2021-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210502_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='newcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='newdeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='totalcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='totaldeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='newcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='newdeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='totalcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='totaldeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='newcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='newdeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='totalcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='totaldeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='newcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='newdeath',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='totalcase',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='totaldeath',
            field=models.BigIntegerField(null=True),
        ),
    ]
